title = "Custom Gitleaks configuration"


[extend]
# useDefault will extend the default gitleaks config built in to the binary
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true



[[allowlists]]
description = "global allow list"

regexTarget = "match"
regexes = [
  '''Pl34s3_7hink_4b0u7_ch4nging_m3_in_pr0d''',
  '''c2VhZmlsZTp6amttaWQ2clFpYmRaPXVKTXVXUw==''',
  '''UGwzNHMzXzdoaW5rXzRiMHU3X2NoNG5naW5nX20zX2luX3ByMGQ=''',
  '''zjkmid6rQibdZ=uJMuWS'''
]