{
 "title": "Flux - Telegraf - Server and Docker",
 "description": "Overview, Disk, Network, Memory and Docker Containers",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "n_cpus",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"n_cpus\")\r\n  |> last()"
   },
   {
    "name": "host",
    "label": "host",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.bucket, tag: \"host\")"
   },
   {
    "name": "memory",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mem\" and\r\n    r.host == \"${host}\" and\r\n    r._field == \"total\"\r\n  )\r\n  |> last()"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system\" and\r\n    r.host == \"${host}\" and\r\n    r._field == \"uptime\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Number of CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"system\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"n_cpus\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mem\" and\r\n    r.host == \"${host}\" and\r\n    r._field == \"total\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r[\"_measurement\"] == \"swap\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"total\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Memory (last)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mem\" and\r\n    r.host == \"${host}\" and\r\n    r._field == \"used_percent\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "CPU (last)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"cpu\" and\r\n    r.host == \"${host}\" and\r\n    r.cpu == \"cpu-total\" and\r\n    r._field == \"usage_idle\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0 + 100.0 }))\r\n  |> toFloat()\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"docker\" and\r\n    r.host == \"${host}\" and\r\n    (r[\"_field\"] == \"n_containers\" or r[\"_field\"] == \"n_containers_paused\" or r[\"_field\"] == \"n_containers_running\" or r[\"_field\"] == \"n_containers_stopped\")\r\n  )\r\n  |> last()",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Images",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"docker\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"n_images\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r[\"_measurement\"] == \"diskio\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"io_time\" and\r\n    r[\"name\"] =~ /^[a-z]+$/\r\n  )\r\n  |> derivative(nonNegative: true, unit: 1ms)\r\n  |> group(columns: [\"name\"])\r\n  |> aggregateWindow(every: 60s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"disk\" and\r\n    r.host == \"${host}\" and\r\n    (r[\"_field\"] == \"free\" or r[\"_field\"] == \"total\")\r\n  )\r\n  |> group(columns: [\"device\"])\r\n  |> pivot(\r\n    rowKey:[\"_time\"],\r\n    columnKey: [\"_field\"],\r\n    valueColumn: \"_value\"\r\n  )\r\n  |> last(column: \"_time\")\r\n  |> group()\r\n  |> keep(columns: [\"free\", \"total\", \"device\"])"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"disk\" and\r\n    r.host == \"${host}\" and\r\n    r._field == \"used_percent\"\r\n  )\r\n  |> group(columns: [\"device\"])\r\n  |> last()"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"cpu\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"usage_idle\" and\r\n    r[\"cpu\"] != \"cpu-total\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: r._value * -1.0 + 100.0 }))\r\n  |> toFloat()\r\n  |> keep(columns: [\"_time\", \"_value\", \"cpu\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Use per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"docker_container_cpu\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"usage_percent\"\r\n  )\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: r._value / float(v: ${n_cpus})\r\n    })\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"container_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"mem\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"used_percent\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"mem\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"used\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Use per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"docker_container_mem\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"usage_percent\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"container_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory Use per Container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"docker_container_mem\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"usage\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\", \"container_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Swap (usage)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r[\"_measurement\"] == \"swap\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"used_percent\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"net\" and\r\n    r.host == \"${host}\" and\r\n    (r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  )\r\n  |> derivative()\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Traffic per Container (Transmitted)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"docker_container_net\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"tx_bytes\"\r\n  )\r\n  |> derivative(nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"_value\", \"container_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Traffic per Container (Received)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"docker_container_net\" and\r\n    r.host == \"${host}\" and\r\n    r[\"_field\"] == \"rx_bytes\"\r\n  )\r\n  |> derivative(nonNegative: true)\r\n  |> keep(columns: [\"_time\", \"_value\", \"container_name\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}