---
- name: 01-SETUP -- Create app_name directory
  ansible.builtin.file:
    state: directory
    path: "{{ project_dir }}/apps/{{ app_name }}"
    owner: "{{ project_dir_owner }}"
    group: "{{ project_dir_group }}"
    mode: "0700"
  become: true

- name: 01-SETUP -- Create app subdirectories
  ansible.builtin.file:
    state: directory
    path: "{{ project_dir }}/apps/{{ app_name }}/{{ item }}"
    owner: "{{ project_dir_owner }}"
    group: "{{ project_dir_group }}"
    mode: "0770"
  loop:
    - data
    - config
    - config/netbox
  become: true

- name: 01-SETUP -- Create subdirs for bitnami apps
  ansible.builtin.file:
    state: directory
    path: "{{ project_dir}}/apps/{{app_name}}/{{item }}"
    mode: "0770"
    owner: "1001"
    group: "{{ project_dir_group }}"
  become: true
  loop:
    - data/postgresql
    - data/redis

- name: 01-SETUP -- create Caddyfile from template
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ project_dir }}/config/caddy-apps/{{ app_name }}"
    owner: "{{ project_dir_owner }}"
    group: "{{ project_dir_group }}"
    mode: "0600"
  become: true

- name: 01-SETUP -- copy template files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ project_dir }}/apps/{{ app_name }}/{{ item }}"
    owner: "{{ project_dir_owner }}"
    group: "{{ project_dir_group }}"
    mode: "0600"
  loop:
    - compose.yml
    - .env
    - config/netbox/configuration.py
  become: true

- name: 01-SETUP -- Add / modify {{ APP }}_INCLUDE_PATH in root .env file
  ansible.builtin.lineinfile:
    path: "{{ project_dir }}/.env"
    regexp: "^{{ app_name | upper }}_COMPOSE_PATH=./apps/{{ app_name }}/compose.yml"
    line: "{{ app_name | upper }}_COMPOSE_PATH=./apps/{{ app_name }}/compose.yml"

- name: 02-START -- (Re)start caddy
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    pull: missing
    state: "{{ item }}"
    services:
      - caddy
  loop:
    - absent
    - present

- name: 02-START -- Take down and init app services
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    pull: missing
    state: present
    services:
      - netbox
      - netbox-db

- name: 99-FINISH - Run pip install for plugins
  ansible.builtin.command:
    cmd: "docker compose exec netbox {{ item }} "
    chdir: "{{ project_dir }}"
  loop: 
    - pip install slurpit_netbox
    - pip install netbox-plugin-dns
    - pip install netbox-topology-views
    - pip install netbox-validity

- name: 99-FINISH - Migrate db and copy static
  ansible.builtin.command:
    cmd: "docker compose exec netbox {{ item }} "
    chdir: "{{ project_dir }}"
  loop: 
    - python3 /app/netbox/netbox/manage.py migrate
    - python3 /app/netbox/netbox/manage.py collectstatic --noinput


- name: 99-FINISH -- Restart netbox
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    state: restarted
    services:
      - netbox

- name: 99-FINISH Wait until app is available on on "https://{{ app_subdomain }}.{{ domain_name }}/login
  uri:
    url: "https://{{ app_subdomain }}.{{ domain_name }}/login"
    return_content: no
    validate_certs: yes
    status_code:
      - 200
  until: site_up_output.status == 200
  retries: 24 # 120 seconds = 2 minutes
  delay: 5
  register: site_up_output

