name: Validate Ansible Syntax

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  ansible-lint:
    name: Ansible Syntax Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Install external ansible roles
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install community.docker
          ansible-galaxy role install geerlingguy.docker


      - name: Validate Ansible playbook syntax
        run: |
          ansible-playbook -i inventory/example --syntax-check site.yml
